CREATE TABLE usuario (
  idusuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  username VARCHAR(20) NOT NULL,
  password_2 VARCHAR(32) NOT NULL,
  profile INTEGER(1) UNSIGNED NOT NULL,
  PRIMARY KEY(idusuario)
);

CREATE TABLE bairro (
  idbairro INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
  nome VARCHAR(20) NOT NULL,
);

INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Aerolândia')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Aeroporto')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Aldeota')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Alto da Balança')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Alvaro Weyne')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Amadeu Furtado')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Ancuri')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Antônio Bezerra')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Aracapé')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Autran Nunes')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Bairro Ellery')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Barra do Ceará')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Barroso')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Bela Vista')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Benfica')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Boa Vista')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Bom Futuro')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Bom Jardim')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Bonsucesso')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cais do Porto')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cajazeiras')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cambeba')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Canindezinho')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Carlito Pamplona')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Centro')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cidade 2000')
  INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cidade dos Funcionários')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Coaçu')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cocó')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Conjunto Ceará 1')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Conjunto Ceará 2')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Conjunto Esperança')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Conjunto Palmeiras')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Couto Fernandes')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Cristo Redentor')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Curió')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Damas')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('De Lourdes')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Demócrito Rocha')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Dendê')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Dias Macedo')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Dionísio Torres')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Dom Lustosa')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Edson Queiroz')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Farias Brito')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Fátima')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Floresta')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Genibaú')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Granja Lisboa')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Granja Portugal')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Guajerú')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Guararapes')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Henrique Jorge')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Itaoca')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Itaperi')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jacarecanga')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jangurussu')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jardim América')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jardim Cearense')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jardim das Oliveiras')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jardim Guanabara')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jardim Iracema')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('João XXIII')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Joaquim Távora')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Jóquei Clube')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('José Bonifácio')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('José de Alencar')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('José Walter')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Lagoa Redonda')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Luciano Cavalcante')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Manuel Dias Branco')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Maraponga')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Meireles')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Messejana')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Mondubim')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Monte Castelo')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Montese')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Moura Brasil')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Mucuripe')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Novo Mondubim')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Olavo Oliveira')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Padre Andrade')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Panamericano')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Papicu')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parangaba')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque Araxá')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque Dois Irmãos')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque Iracema')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parquelândia')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque Manibura')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque Santa Rosa')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parque São José')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Parreão')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Passaré')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Paupina')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Pedras')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Pici')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Pirambu')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Planalto Ayrton Senna')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Praia de Iracema')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Praia do Futuro I')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Praia do Futuro II')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Presidente Kennedy')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Presidente Vargas')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Quintino Cunha')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Rodolfo Teófilo')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Sabiaguaba')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Salinas')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Santa Maria')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('São Bento')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('São Gerardo')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('São João do Tauape')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Sapiranga')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Serrinha')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Siqueira')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Varjota')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Vicente Pinzon')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Vila Manuel Sátiro')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Vila Peri')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Vila União')
INSERT INTO APP.BAIRRO (NOME) 
	VALUES ('Vila Velha')

CREATE TABLE endereco(
    id_endereco INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    logradouro VARCHAR(25) NOT NULL,
    numero VARCHAR(5) NOT NULL,
    complemento VARCHAR(20),
    bairro VARCHAR(25),
    cep VARCHAR(10)
);

CREATE TABLE Cliente (
  idCliente INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
  endereco_idendereco INTEGER NOT NULL,
  nome VARCHAR(20) NOT NULL,
  sobre_nome VARCHAR(20),
  cpf VARCHAR(15) UNIQUE,
  fone VARCHAR(15) NOT NULL,
  CONSTRAINT endereco_id_ref FOREIGN KEY(endereco_idendereco)
    REFERENCES endereco(id_endereco)
);

CREATE TABLE ordem_servico (
  idordem_servico INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Cliente_idCliente INTEGER UNSIGNED NOT NULL,
  usuario_idusuario INTEGER UNSIGNED NOT NULL,
  date_os DATETIME NOT NULL,
  defeito VARCHAR(150) NOT NULL,
  servico VARCHAR(150) NOT NULL,
  valor DOUBLE PRECISION NULL,
  status_2 INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idordem_servico),
  INDEX ordem_servico_FKIndex1(usuario_idusuario),
  INDEX ordem_servico_FKIndex2(Cliente_idCliente),
  FOREIGN KEY(usuario_idusuario)
    REFERENCES usuario(idusuario)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(Cliente_idCliente)
    REFERENCES Cliente(idCliente)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE equipamento (
  idequipamento INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Cliente_idCliente INTEGER UNSIGNED NOT NULL,
  processador VARCHAR(20) NOT NULL,
  placa_mae VARCHAR(20) NOT NULL,
  memoria_ram VARCHAR(20) NOT NULL,
  memoria VARCHAR(20) NOT NULL,
  gabinete VARCHAR(20) NULL,
  PRIMARY KEY(idequipamento),
  INDEX equipamento_FKIndex1(Cliente_idCliente),
  FOREIGN KEY(Cliente_idCliente)
    REFERENCES Cliente(idCliente)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


# Consultas

SELECT c.IDCLIENTE, c.NOME, c.SOBRE_NOME, c.CPF, c.FONE, e.* FROM cliente as c JOIN endereco as e on e.ID_ENDERECO = c.ENDERECO_IDENDERECO WHERE c.IDCLIENTE = 1;